# Generated by Django 4.1 on 2022-08-30 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Tillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tillage_type', models.CharField(max_length=32)),
                ('harvest_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OcurredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHUVA EXCESSIVA', 1), ('GEADA', 2), ('GRANIZO', 3), ('SECA', 4), ('VENDAVAL', 5), ('RAIO', 6)], max_length=15)),
                ('date', models.DateField()),
                ('tillage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proagro.tillage')),
            ],
        ),
    ]
