# Generated by Django 4.1 on 2022-08-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proagro', '0002_tillage_productor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ocurredevent',
            name='type',
            field=models.CharField(choices=[('EXCESSIVE_RAIN', 'CHUVA EXCESSIVA'), ('FROST', 'GEADA'), ('HAIL', 'GRANIZO'), ('DRY', 'SECA'), ('GALE', 'VENDAVAL'), ('LIGHTNING', 'RAIO')], max_length=15),
        ),
    ]
